name: Test
on:
 push:
  paths:
    - 'dev-server/**'
jobs:
   test:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: [14.x]
    name: Run tests
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install npm dependencies
        run: npm install
      - name: Run jest unit tests
        run: npm test
      - name: Run Cypress end-to-end
        uses: cypress-io/github-action@v1
        with:
          # we have already installed all dependencies above
          install: false
          start: npm run cy:cli
